/**
 * Accounts — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `landmark`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { SELF_BOX, SVG_BASE, stagger } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Accounts = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Accounts({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <motion.path d={"M10 18v-7"} variants={stagger(1)} animate={state} style={SELF_BOX} />
                <path d={"M11.12 2.198a2 2 0 0 1 1.76.006l7.866 3.847c.476.233.31.949-.22.949H3.474c-.53 0-.695-.716-.22-.949z"} />
                <motion.path d={"M14 18v-7"} variants={stagger(2)} animate={state} style={SELF_BOX} />
                <motion.path d={"M18 18v-7"} variants={stagger(3)} animate={state} style={SELF_BOX} />
                <path d={"M3 22h18"} />
                <motion.path d={"M6 18v-7"} variants={stagger(0)} animate={state} style={SELF_BOX} />
            </svg>
        );
    },
);

export default Accounts;
