/**
 * AiExtractions — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `sparkles`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { SELF_BOX, SVG_BASE, stagger } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const AiExtractions = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function AiExtractions({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <path d={"M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"} />
                <motion.path d={"M20 3v4"} variants={stagger(0)} animate={state} style={SELF_BOX} />
                <motion.path d={"M22 5h-4"} variants={stagger(1)} animate={state} style={SELF_BOX} />
                <motion.path d={"M4 17v2"} variants={stagger(2)} animate={state} style={SELF_BOX} />
                <motion.path d={"M5 18H3"} variants={stagger(3)} animate={state} style={SELF_BOX} />
            </svg>
        );
    },
);

export default AiExtractions;
