/**
 * Approvals — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `clipboard-check`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Approvals = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Approvals({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <rect width={"8"} height={"4"} x={"8"} y={"2"} rx={"1"} ry={"1"} />
                <path d={"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"} />
                <motion.path d={"m9 14 2 2 4-4"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
            </svg>
        );
    },
);

export default Approvals;
