/**
 * AuditTrail — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `shield-check`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const AuditTrail = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function AuditTrail({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <path d={"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"} />
                <motion.path d={"m9 12 2 2 4-4"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
            </svg>
        );
    },
);

export default AuditTrail;
