/**
 * Bell — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `bell`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, SVG_BASE, SWING } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Bell = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Bell({ size = 24, state, ...rest }, ref) {
        return (
            <motion.svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                variants={SWING}
                animate={state}
                transition={DEFAULT_TRANSITION}
                style={{ transformOrigin: "50% 15%" }}
                {...rest}
            >
                <path d={"M10.268 21a2 2 0 0 0 3.464 0"} />
                <path d={"M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"} />
            </motion.svg>
        );
    },
);

export default Bell;
