/**
 * ChevronRight — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `chevron-right`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, NUDGE_X, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const ChevronRight = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function ChevronRight({ size = 24, state, ...rest }, ref) {
        return (
            <motion.svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                variants={NUDGE_X}
                animate={state}
                transition={DEFAULT_TRANSITION}
                {...rest}
            >
                <path d={"m9 18 6-6-6-6"} />
            </motion.svg>
        );
    },
);

export default ChevronRight;
