/**
 * CloseCircle — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `circle-x`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const CloseCircle = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function CloseCircle({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <circle cx={"12"} cy={"12"} r={"10"} />
                <motion.path d={"m15 9-6 6"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <motion.path d={"m9 9 6 6"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
            </svg>
        );
    },
);

export default CloseCircle;
