/**
 * Contacts — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `users`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Contacts = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Contacts({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <path d={"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"} />
                <motion.path d={"M16 3.128a4 4 0 0 1 0 7.744"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <motion.path d={"M22 21v-2a4 4 0 0 0-3-3.87"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <circle cx={"9"} cy={"7"} r={"4"} />
            </svg>
        );
    },
);

export default Contacts;
