/**
 * Dashboard — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `house`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Dashboard = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Dashboard({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <motion.path d={"M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <path d={"M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"} />
            </svg>
        );
    },
);

export default Dashboard;
