/**
 * Download — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `download`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, NUDGE_Y, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Download = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Download({ size = 24, state, ...rest }, ref) {
        return (
            <motion.svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                variants={NUDGE_Y}
                animate={state}
                transition={DEFAULT_TRANSITION}
                {...rest}
            >
                <path d={"M12 15V3"} />
                <path d={"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"} />
                <motion.path d={"m7 10 5 5 5-5"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
            </motion.svg>
        );
    },
);

export default Download;
