/**
 * Edit — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `square-pen`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Edit = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Edit({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <path d={"M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"} />
                <motion.path d={"M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
            </svg>
        );
    },
);

export default Edit;
