/**
 * FixedAssets — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `building-2`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { SELF_BOX, SVG_BASE, stagger } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const FixedAssets = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function FixedAssets({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <path d={"M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"} />
                <path d={"M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2"} />
                <path d={"M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2"} />
                <motion.path d={"M10 6h4"} variants={stagger(0)} animate={state} style={SELF_BOX} />
                <motion.path d={"M10 10h4"} variants={stagger(1)} animate={state} style={SELF_BOX} />
                <motion.path d={"M10 14h4"} variants={stagger(2)} animate={state} style={SELF_BOX} />
                <motion.path d={"M10 18h4"} variants={stagger(3)} animate={state} style={SELF_BOX} />
            </svg>
        );
    },
);

export default FixedAssets;
