import Dashboard from "./dashboard";
import Purchases from "./purchases";
import Inventory from "./inventory";
import Sales from "./sales";
import Contacts from "./contacts";
import Accounts from "./accounts";
import Taxation from "./taxation";
import FixedAssets from "./fixed-assets";
import Reports from "./reports";
import Payroll from "./payroll";
import AuditTrail from "./audit-trail";
import Approvals from "./approvals";
import AiExtractions from "./ai-extractions";
import Bell from "./bell";
import Settings from "./settings";
import Search from "./search";
import ChevronRight from "./chevron-right";
import Plus from "./plus";
import PanelClose from "./panel-close";
import PanelOpen from "./panel-open";
import MoreVertical from "./more-vertical";
import CloseCircle from "./close-circle";
import Trash from "./trash";
import Edit from "./edit";
import Download from "./download";
import Refresh from "./refresh";
import TrendUp from "./trend-up";
import TrendDown from "./trend-down";
import type { VariantMap } from "./loader";

/**
 * The lazy chunk root. Everything reachable from here — `motion/react`
 * included — is code-split out of the initial bundle, which is enforced by the
 * `motion-outside-chunk` rule in scripts/check-legacy-tokens.mjs.
 *
 * Generated by scripts/gen-icon-variants.mjs. Do not edit by hand.
 */
export const ANIMATED_VARIANTS: VariantMap = {
    "dashboard": Dashboard,
    "purchases": Purchases,
    "inventory": Inventory,
    "sales": Sales,
    "contacts": Contacts,
    "accounts": Accounts,
    "taxation": Taxation,
    "fixed-assets": FixedAssets,
    "reports": Reports,
    "payroll": Payroll,
    "audit-trail": AuditTrail,
    "approvals": Approvals,
    "ai-extractions": AiExtractions,
    "bell": Bell,
    "settings": Settings,
    "search": Search,
    "chevron-right": ChevronRight,
    "plus": Plus,
    "panel-close": PanelClose,
    "panel-open": PanelOpen,
    "more-vertical": MoreVertical,
    "close-circle": CloseCircle,
    "trash": Trash,
    "edit": Edit,
    "download": Download,
    "refresh": Refresh,
    "trend-up": TrendUp,
    "trend-down": TrendDown,
};
