/**
 * MoreVertical — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `ellipsis-vertical`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { SELF_BOX, SVG_BASE, stagger } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const MoreVertical = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function MoreVertical({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <motion.circle cx={"12"} cy={"12"} r={"1"} variants={stagger(1)} animate={state} style={SELF_BOX} />
                <motion.circle cx={"12"} cy={"5"} r={"1"} variants={stagger(0)} animate={state} style={SELF_BOX} />
                <motion.circle cx={"12"} cy={"19"} r={"1"} variants={stagger(2)} animate={state} style={SELF_BOX} />
            </svg>
        );
    },
);

export default MoreVertical;
