/**
 * PanelClose — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `panel-left-close`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const PanelClose = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function PanelClose({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <rect width={"18"} height={"18"} x={"3"} y={"3"} rx={"2"} />
                <path d={"M9 3v18"} />
                <motion.path d={"m16 15-3-3 3-3"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
            </svg>
        );
    },
);

export default PanelClose;
