/**
 * Payroll — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `briefcase`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Payroll = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Payroll({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <motion.path d={"M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <rect width={"20"} height={"14"} x={"2"} y={"6"} rx={"2"} />
            </svg>
        );
    },
);

export default Payroll;
