/**
 * Plus — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `plus`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, SPIN_HALF, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Plus = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Plus({ size = 24, state, ...rest }, ref) {
        return (
            <motion.svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                variants={SPIN_HALF}
                animate={state}
                transition={DEFAULT_TRANSITION}
                {...rest}
            >
                <path d={"M5 12h14"} />
                <path d={"M12 5v14"} />
            </motion.svg>
        );
    },
);

export default Plus;
