/**
 * Purchases — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `shopping-bag`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Purchases = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Purchases({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <motion.path d={"M16 10a4 4 0 0 1-8 0"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <path d={"M3.103 6.034h17.794"} />
                <path d={"M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z"} />
            </svg>
        );
    },
);

export default Purchases;
