/**
 * Refresh — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `refresh-cw`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, SPIN, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Refresh = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Refresh({ size = 24, state, ...rest }, ref) {
        return (
            <motion.svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                variants={SPIN}
                animate={state}
                transition={DEFAULT_TRANSITION}
                {...rest}
            >
                <path d={"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"} />
                <path d={"M21 3v5h-5"} />
                <path d={"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"} />
                <path d={"M8 16H3v5"} />
            </motion.svg>
        );
    },
);

export default Refresh;
