/**
 * Reports — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `chart-no-axes-column`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { SELF_BOX, SVG_BASE, stagger } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Reports = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Reports({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <motion.line x1={"18"} x2={"18"} y1={"20"} y2={"10"} variants={stagger(2)} animate={state} style={SELF_BOX} />
                <motion.line x1={"12"} x2={"12"} y1={"20"} y2={"4"} variants={stagger(1)} animate={state} style={SELF_BOX} />
                <motion.line x1={"6"} x2={"6"} y1={"20"} y2={"14"} variants={stagger(0)} animate={state} style={SELF_BOX} />
            </svg>
        );
    },
);

export default Reports;
