/**
 * Sales — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `receipt`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Sales = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Sales({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <path d={"M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z"} />
                <motion.path d={"M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <motion.path d={"M12 17.5v-11"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
            </svg>
        );
    },
);

export default Sales;
