/**
 * Search — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `search`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, POP, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Search = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Search({ size = 24, state, ...rest }, ref) {
        return (
            <motion.svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                variants={POP}
                animate={state}
                transition={DEFAULT_TRANSITION}
                {...rest}
            >
                <motion.path d={"m21 21-4.34-4.34"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <circle cx={"11"} cy={"11"} r={"8"} />
            </motion.svg>
        );
    },
);

export default Search;
