/**
 * Settings — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `settings`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, SPIN_HALF, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Settings = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Settings({ size = 24, state, ...rest }, ref) {
        return (
            <motion.svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                variants={SPIN_HALF}
                animate={state}
                transition={DEFAULT_TRANSITION}
                {...rest}
            >
                <path d={"M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"} />
                <circle cx={"12"} cy={"12"} r={"3"} />
            </motion.svg>
        );
    },
);

export default Settings;
