/**
 * Taxation — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `percent`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Taxation = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Taxation({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <motion.line x1={"19"} x2={"5"} y1={"5"} y2={"19"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <circle cx={"6.5"} cy={"6.5"} r={"2.5"} />
                <circle cx={"17.5"} cy={"17.5"} r={"2.5"} />
            </svg>
        );
    },
);

export default Taxation;
