/**
 * Trash — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `trash-2`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const Trash = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function Trash({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <path d={"M3 6h18"} />
                <path d={"M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"} />
                <path d={"M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"} />
                <motion.line x1={"10"} x2={"10"} y1={"11"} y2={"17"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <motion.line x1={"14"} x2={"14"} y1={"11"} y2={"17"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
            </svg>
        );
    },
);

export default Trash;
