/**
 * TrendDown — generated by scripts/gen-icon-variants.mjs from lucide-react's
 * `arrow-down-left`. Do not edit by hand: run `npm run gen:icons`.
 *
 * The geometry is lucide's, verbatim, so this is pixel-identical to the static
 * icon at rest. The motion recipes come from variants/shared.ts.
 */
import { motion } from "motion/react";
import { forwardRef } from "react";

import { DEFAULT_TRANSITION, DRAW, SVG_BASE } from "./shared";
import type { AnimatedIconVariantProps } from "./types";

const TrendDown = forwardRef<SVGSVGElement, AnimatedIconVariantProps>(
    function TrendDown({ size = 24, state, ...rest }, ref) {
        return (
            <svg
                ref={ref}
                {...SVG_BASE}
                width={size}
                height={size}
                {...rest}
            >
                <motion.path d={"M17 7 7 17"} variants={DRAW} animate={state} transition={DEFAULT_TRANSITION} />
                <path d={"M17 17H7V7"} />
            </svg>
        );
    },
);

export default TrendDown;
