const BASE_URL = import.meta.env.VITE_API_BASE_URL;
const API_BASE_URL = BASE_URL + "/api";
const Constants = {
  API_BASE_URL,
  BASE_URL,
  LOGIN_URL: `${API_BASE_URL}/auth/login`,
  REGISTER_URL: `${API_BASE_URL}/auth/register`,
  APP_VERSION_URL: `${API_BASE_URL}/admin/app-version`,
  FETCH_SETUP_DROPDOWNS_URL: `${API_BASE_URL}/admin/settings-dropdown`,
  UPDATE_COMPANY_SETUP_URL: `${API_BASE_URL}/admin/company/setup`,
  FETCH_USER_PROFILE_URL: `${API_BASE_URL}/admin/profile`,
  FETCH_COUNTRIES_URL: `${API_BASE_URL}/admin/countries`,
  FETCH_STATES_URL: `${API_BASE_URL}/admin/states`,
  FETCH_CITIES_URL: `${API_BASE_URL}/admin/cities`,
  UPDATE_PROFILE_URL: `${API_BASE_URL}/admin/profile`,
  FETCH_UNITS_URL: `${API_BASE_URL}/admin/units`,
  CREATE_UNIT_URL: `${API_BASE_URL}/admin/units`,
  GET_UNIT_URL: `${API_BASE_URL}/admin/units`,
  UPDATE_UNIT_URL: `${API_BASE_URL}/admin/units`,
  DELETE_UNIT_URL: `${API_BASE_URL}/admin/units`,
  CREATE_BRAND_URL: `${API_BASE_URL}/admin/brands`,
  FETCH_BRAND_LIST_URL: `${API_BASE_URL}/admin/brands`,
  GET_BRAND_URL: `${API_BASE_URL}/admin/brands`,
  UPDATE_BRAND_URL: `${API_BASE_URL}/admin/brands`,
  DELETE_BRAND_URL: `${API_BASE_URL}/admin/brands`,
  FETCH_CATEGORY_LIST_URL: `${API_BASE_URL}/admin/categories`,
  CREATE_CATEGORY_URL: `${API_BASE_URL}/admin/categories`,
  UPDATE_CATEGORY_URL: `${API_BASE_URL}/admin/categories`,
  GET_CATEGORY_URL: `${API_BASE_URL}/admin/categories`,
  DELETE_CATEGORY_URL: `${API_BASE_URL}/admin/categories`,
  CREATE_TAX_RATE_URL: `${API_BASE_URL}/admin/tax-rates`,
  FETCH_TAX_RATE_LIST_URL: `${API_BASE_URL}/admin/tax-rates`,
  GET_TAX_RATE_URL: `${API_BASE_URL}/admin/tax-rates`,
  UPDATE_TAX_RATE_URL: `${API_BASE_URL}/admin/tax-rates`,
  DELETE_TAX_RATE_URL: `${API_BASE_URL}/admin/tax-rates`,
  GET_TAX_RATES_FOR_LIST_URL: `${API_BASE_URL}/admin/tax-rates`,
  GET_TAX_RATE_FOR_EDIT_URL: `${API_BASE_URL}/admin/tax-rates`,
  FETCH_TAX_GROUP_LIST_URL: `${API_BASE_URL}/admin/tax-groups`,
  CREATE_TAX_GROUP_URL: `${API_BASE_URL}/admin/tax-groups`,
  GET_TAX_GROUP_URL: `${API_BASE_URL}/admin/tax-groups`,
  UPDATE_TAX_GROUP_URL: `${API_BASE_URL}/admin/tax-groups`,
  DELETE_TAX_GROUP_URL: `${API_BASE_URL}/admin/tax-groups`,
  FETCH_PRODUCTS_URL: `${API_BASE_URL}/admin/products`,
  GET_PRODUCT_URL: `${API_BASE_URL}/admin/products`,
  FETCH_PRODUCT_CATEGORIES_URL: `${API_BASE_URL}/admin/product-categories`,
  FETCH_PRODUCT_BRANDS_URL: `${API_BASE_URL}/admin/product-brands`,
  FETCH_PRODUCT_UNITS_URL: `${API_BASE_URL}/admin/product-units`,
  FETCH_PRODUCT_TAXES_URL: `${API_BASE_URL}/admin/product-taxes`,
  CREATE_PRODUCT_URL: `${API_BASE_URL}/admin/products`,
  UPDATE_PRODUCT_URL: `${API_BASE_URL}/admin/products`,
  DELETE_PRODUCT_URL: `${API_BASE_URL}/admin/products`,
  CREATE_SUPPLIER_URL: `${API_BASE_URL}/admin/suppliers`,
  GET_SUPPLIERS_URL: `${API_BASE_URL}/admin/suppliers`,
  UPDATE_SUPPLIER_URL: `${API_BASE_URL}/admin/suppliers`,
  DELETE_SUPPLIER_URL: `${API_BASE_URL}/admin/suppliers`,
  GET_SIGNATURES_URL: `${API_BASE_URL}/admin/signatures`,
  CREATE_SIGNATURE_URL: `${API_BASE_URL}/admin/signatures`,
  UPDATE_SIGNATURE_URL: `${API_BASE_URL}/admin/signatures`,
  DELETE_SIGNATURE_URL: `${API_BASE_URL}/admin/signatures`,
  UPDATE_SIGNATURE_STATUS_URL: `${API_BASE_URL}/admin/signatures/status`,
  UPDATE_SIGNATURE_DEFAULT_URL: `${API_BASE_URL}/admin/signatures/set-default`,
  GET_BANK_ACCOUNTS_URL: `${API_BASE_URL}/admin/bank-accounts`,
  CREATE_BANK_ACCOUNT_URL: `${API_BASE_URL}/admin/bank-accounts`,
  UPDATE_BANK_ACCOUNT_URL: `${API_BASE_URL}/admin/bank-accounts`,
  DELETE_BANK_ACCOUNT_URL: `${API_BASE_URL}/admin/bank-accounts`,
  RESTORE_BANK_ACCOUNT_URL: `${API_BASE_URL}/admin/bank-accounts/restore`, // append /${id}
  UPDATE_BANK_ACCOUNT_STATUS_URL: `${API_BASE_URL}/admin/bank-accounts/status`,
  UPDATE_COMPANY_SETTINGS_URL: `${API_BASE_URL}/admin/company-details`,
  FETCH_COMPANY_SETTINGS_URL: `${API_BASE_URL}/admin/company-details`,
  FETCH_COUNTRY_URL: `${API_BASE_URL}/admin/country`,
  FETCH_STATE_URL: `${API_BASE_URL}/admin/state`,
  FETCH_CITY_URL: `${API_BASE_URL}/admin/city`,
  FETCH_USERS_URL: `${API_BASE_URL}/admin/user/type`,
  FETCH_USER_BY_ID_URL: `${API_BASE_URL}/admin/user`,
  FETCH_PRODUCTS_WITH_SEARCH_URL: `${API_BASE_URL}/admin/productsrecent`,
  FETCH_TAX_GROUPS_URL: `${API_BASE_URL}/admin/tax-group-details`,
  FETCH_BANK_ACCOUNTS_WITH_SEARCH_URL: `${API_BASE_URL}/admin/bankdetailsrecent`,
  FETCH_SIGNATURES_WITH_SEARCH_URL: `${API_BASE_URL}/admin/signaturesrecent`,
  CREATE_PURCHASE_ORDER_URL: `${API_BASE_URL}/admin/purchase-order`,
  FETCH_PURCHASE_ORDERS_URL: `${API_BASE_URL}/admin/purchase-orders`,
  DELETE_PURCHASE_ORDER_URL: `${API_BASE_URL}/admin/purchase-orders`,
  FETCH_PURCHASE_ORDER_URL: `${API_BASE_URL}/admin/purchase-orders`,
  UPDATE_PURCHASE_ORDER_URL: `${API_BASE_URL}/admin/purchase-orders`,
  GET_ALL_PAYMENT_MODES_URL: `${API_BASE_URL}/admin/paymentmode`,
  CREATE_PAYMENT_MODE_URL: `${API_BASE_URL}/admin/paymentmode`,
  GET_PURCHASE_ORDERS_MINIMAL_URL: `${API_BASE_URL}/admin/purchase-minimal`,
  CREATE_NEW_PURCHASE_URL: `${API_BASE_URL}/admin/purchases`,
  GET_PURCHASE_URL: `${API_BASE_URL}/admin/purchases`,
  FETCH_PURCHASE_DETAILS_URL: `${API_BASE_URL}/admin/purchases`,
  UPDATE_PURCHASE_URL: `${API_BASE_URL}/admin/purchases`,
  DELETE_PURCHASE_URL: `${API_BASE_URL}/admin/purchases`,
  GET_SUPPLIER_PAYMENTS_URL: `${API_BASE_URL}/admin/supplierpayments`,
  GET_SUPPLIER_BALANCES_URL: `${API_BASE_URL}/admin/reports/supplier-balances`,
  FETCH_ALL_PURCHASE_FOR_DEBIT_NOTE_URL: `${API_BASE_URL}/admin/purchases-minimal`,
  GET_PURCHASE_DETAILS_URL: `${API_BASE_URL}/admin/purchases`,
  CREATE_DEBIT_NOTE_URL: `${API_BASE_URL}/admin/debitnote`,
  FETCH_FOR_DEBIT_NOTE_LIST_URL: `${API_BASE_URL}/admin/debitnote`,
  GET_DEBIT_NOTE_DETAILS_URL: `${API_BASE_URL}/admin/debitnote`, // by-id call: `${GET_DEBIT_NOTE_DETAILS_URL}/${id}`
  DELETE_DEBIT_NOTE_URL: `${API_BASE_URL}/admin/debitnote`,
  DELETE_SUPPLIER_PAYMENT_URL: `${API_BASE_URL}/admin/supplierpayments`,
  CREATE_SUPPLIER_PAYMENT_URL: `${API_BASE_URL}/admin/supplierpayments`,
  UPDATE_SUPPLIER_PAYMENT_URL: `${API_BASE_URL}/admin/supplierpayments`,
  GET_ALL_PENDING_PURCHASES_URL: `${API_BASE_URL}/admin/purchases-pending`,
  CREATE_NEW_CURRENCY_URL: `${API_BASE_URL}/admin/currency`,
  GET_CURRENCIES_URL: `${API_BASE_URL}/admin/currency`,
  UPDATE_CURRENCY_STATUS_URL: `${API_BASE_URL}/admin/currency`,
  UPDATE_CURRENCY_URL: `${API_BASE_URL}/admin/currency`,
  DELETE_CURRENCY_URL: `${API_BASE_URL}/admin/currency`,
  CREATE_CUSTOMER_URL: `${API_BASE_URL}/admin/customers`,
  GET_CUSTOMERS_FOR_LIST_URL: `${API_BASE_URL}/admin/customers`,
  GET_CUSTOMER_FOR_EDIT_URL: `${API_BASE_URL}/admin/customers`,
  CREATE_CUSTOMER_MINIMAL_URL: `${API_BASE_URL}/admin/customers/minimal`,
  UPDATE_CUSTOMER_URL: `${API_BASE_URL}/admin/customers`,
  DELETE_CUSTOMER_URL: `${API_BASE_URL}/admin/customers`,
  // Contacts delete (backend: DELETE /admin/contacts/:id, gated by the `customers` module)
  DELETE_CONTACT_URL: `${API_BASE_URL}/admin/contacts`,
  // Contacts CSV import/export — writes/reads the unified Contact table directly
  // (distinct from the legacy IMPORT_CUSTOMERS_URL which only touches Customer rows)
  IMPORT_CONTACTS_URL: `${API_BASE_URL}/admin/contacts/import`,
  CONFIRM_IMPORT_CONTACTS_URL: `${API_BASE_URL}/admin/contacts/import/confirm`,
  EXPORT_CONTACTS_URL: `${API_BASE_URL}/admin/contacts/export`,
  CREATE_VEHICLE_URL: `${API_BASE_URL}/admin/vehicles`,
  GET_VEHICLES_FOR_LIST_URL: `${API_BASE_URL}/admin/vehicles`,
  GET_VEHICLE_FOR_EDIT_URL: `${API_BASE_URL}/admin/vehicles`,
  UPDATE_VEHICLE_URL: `${API_BASE_URL}/admin/vehicles`,
  DELETE_VEHICLE_URL: `${API_BASE_URL}/admin/vehicles`,
  GET_VEHICLES_FOR_CUSTOMER_URL: `${API_BASE_URL}/admin/customers`, // call site appends /${customerId}/vehicles
  FETCH_LOCALIZATION_DROPDOWNS_URL: `${API_BASE_URL}/admin/localization`,
  UPDATE_LOCALIZATION_URL: `${API_BASE_URL}/admin/localizations`,
  CREATE_QUOTATION_URL: `${API_BASE_URL}/admin/quotations`,
  GET_CUSTOMERS_WITH_SEARCH_URL: `${API_BASE_URL}/admin/customers-all`,
  GET_QUOTATIONS_FOR_LIST_URL: `${API_BASE_URL}/admin/quotations`,
  DELETE_QUOTATION_URL: `${API_BASE_URL}/admin/quotations`,
  FETCH_QUOTATION_DETAILS_URL: `${API_BASE_URL}/admin/quotations`,
  UPDATE_QUOTATION_URL: `${API_BASE_URL}/admin/quotations`,
  MAKE_INVOICE_TEMPLATE_DEFAULT_URL: `${API_BASE_URL}/admin/invoice-template`,
  FETCH_DEFAULT_INVOICE_TEMPLATE_URL: `${API_BASE_URL}/admin/invoice-templates`,
  CREATE_NEW_INVOICE_URL: `${API_BASE_URL}/admin/invoices`,
  GET_INVOICES_FOR_LIST_URL: `${API_BASE_URL}/admin/invoices`,
  CONVERT_QUOTATION_TO_INVOICE_URL: `${API_BASE_URL}/admin/quotation-convert-to-invoice`,
  CONVERT_PROFORMA_TO_INVOICE_URL: `${API_BASE_URL}/admin/invoices`, // call site appends /${id}/convert-to-invoice
  DELETE_INVOICE_URL: `${API_BASE_URL}/admin/invoices`,
  FETCH_INVOICE_FOR_EDIT_URL: `${API_BASE_URL}/admin/invoices`,
  // NOTE: this route IS protect-guarded — always send an Authorization header when calling it.
  FETCH_INVOICE_DETAILS_NO_AUTH_URL: `${API_BASE_URL}/admin/invoices/details`,
  UPDATE_INVOICE_URL: `${API_BASE_URL}/admin/invoices`,
  FETCH_INVOICE_PAYMENT_DETAILS_URL: `${API_BASE_URL}/admin/invoice-payment-details`,
  CREATE_INVOICE_PAYMENT_URL: `${API_BASE_URL}/admin/invoice/payment`,
  SEARCH_INVOICES_FOR_CREDIT_NOTE_URL: `${API_BASE_URL}/admin/invoices-minimal`,
  SEARCH_INVOICES_FOR_DELIVERY_CHALLAN_URL: `${API_BASE_URL}/admin/invoices-minimal-delivery`,
  SEND_INVOICE_MAIL_URL: `${API_BASE_URL}/admin/invoices/mail`,
  UPDATE_INVOICE_STATUS_URL: `${API_BASE_URL}/admin/invoices/update-status`,
  MARK_INVOICE_SENT_URL: `${API_BASE_URL}/admin/invoices`, // append /${id}/mark-sent
  // Recurring Invoice SCHEDULES (non-posting templates; separate from invoices).
  // list/create at the base URL; append /${id} for GET/PUT, /${id}/pause etc.
  // NOTE: the legacy isRecurring-on-Invoice URLs (recurring-invoices,
  // invoices/:id/children, run-recurring-now, recurring-status) are retired.
  RECURRING_SCHEDULES_URL: `${API_BASE_URL}/admin/recurring-schedules`,
  ENABLE_PUBLIC_LINK_URL: `${API_BASE_URL}/admin/invoices`,   // append /${id}/enable-public-link
  DISABLE_PUBLIC_LINK_URL: `${API_BASE_URL}/admin/invoices`,  // append /${id}/disable-public-link
  ROTATE_PUBLIC_LINK_URL: `${API_BASE_URL}/admin/invoices`,   // append /${id}/rotate-public-link
  ENABLE_QUOTATION_PUBLIC_LINK_URL: `${API_BASE_URL}/admin/quotations`, // append /${id}/enable-public-link
  GET_PUBLIC_INVOICE_URL: `${API_BASE_URL}/public/invoices`,  // append /${token} (no auth)
  GET_PUBLIC_QUOTATION_URL: `${API_BASE_URL}/public/quotations`, // append /${token} (no auth)
  FETCH_SYSTEM_SETTINGS_URL: `${API_BASE_URL}/admin/system-settings`,
  CREATE_NEW_CREDIT_NOTE_URL: `${API_BASE_URL}/admin/credit-notes`,
  CREDIT_NOTE_LIST_URL: `${API_BASE_URL}/admin/credit-notes`,
  DELETE_CREDIT_NOTE_URL: `${API_BASE_URL}/admin/credit-notes`,
  FETCH_CREDIT_NOTE_FOR_EDIT_URL: `${API_BASE_URL}/admin/credit-notes`,
  UPDATE_CREDIT_NOTE_URL: `${API_BASE_URL}/admin/credit-notes`,
  FETCH_INVENTORY_LIST_URL: `${API_BASE_URL}/admin/inventory`,
  UPDATE_INVENTORY_URL: `${API_BASE_URL}/admin/inventory`,
  FETCH_INVENTORY_HISTORY_URL: `${API_BASE_URL}/admin/inventory/history`,
  UPDATE_EMAIL_SETTINGS_URL: `${API_BASE_URL}/admin/email-settings`,
  GET_EMAIL_SETTINGS_URL: `${API_BASE_URL}/admin/email-settings`,
  SEND_TEST_EMAIL_URL: `${API_BASE_URL}/admin/email-settings/test`,
  CREATE_ROLE_URL: `${API_BASE_URL}/admin/roles`,
  UPDATE_ROLE_URL: `${API_BASE_URL}/admin/roles`,
  DELETE_ROLE_URL: `${API_BASE_URL}/admin/roles`,
  FETCH_ROLES_FOR_LIST_URL: `${API_BASE_URL}/admin/roles`,
  CREATE_DELIVERY_CHALLAN_URL: `${API_BASE_URL}/admin/delivery-challan`,
  FETCH_DELIVERY_CHALLAN_FOR_LIST_URL: `${API_BASE_URL}/admin/delivery-challan`,
  DELETE_DELIVERY_CHALLAN_URL: `${API_BASE_URL}/admin/delivery-challan`,
  FETCH_DELIVERY_CHALLAN_FOR_EDIT_URL: `${API_BASE_URL}/admin/delivery-challan`,
  UPDATE_DELIVERY_CHALLAN_URL: `${API_BASE_URL}/admin/delivery-challan`,
  FETCH_ALL_ROLES_URL: `${API_BASE_URL}/admin/roles-minimal`,
  CREATE_STAFF_URL: `${API_BASE_URL}/admin/staff`,
  FETCH_STAFF_FOR_LIST_URL: `${API_BASE_URL}/admin/staff`,
  FETCH_MODULES_URL: `${API_BASE_URL}/admin/module-hierarchy`,
  SAVE_PERMISSIONS_URL: `${API_BASE_URL}/admin/permissions`,
  FETCH_ROLE_PERMISSIONS_URL: `${API_BASE_URL}/admin/permissions`,
  UPDATE_STAFF_URL: `${API_BASE_URL}/admin/staff`,
  DELETE_STAFF_URL: `${API_BASE_URL}/admin/staff`,
  GET_ALL_NOTIFICATION_TYPES_URL: `${API_BASE_URL}/admin/notification-types`,
  CREATE_EMAIL_TEMPLATE_URL: `${API_BASE_URL}/admin/email-template`,
  GET_EMAIL_TEMPLATES_URL: `${API_BASE_URL}/admin/email-template`,
  DELETE_EMAIL_TEMPLATE_URL: `${API_BASE_URL}/admin/email-template`,
  UPDATE_EMAIL_TEMPLATE_URL: `${API_BASE_URL}/admin/email-template`,
  RESOLVE_EMAIL_TEMPLATE_URL: `${API_BASE_URL}/admin/email-template/resolve`, // append /${docType}/${id}
  RESOLVE_LINE_TAX_URL: `${API_BASE_URL}/admin/tax-engine/resolve-line`,
  GET_PURCHASE_REPORT_URL: `${API_BASE_URL}/admin/report/purchase`,
  GET_PURCHASE_ORDER_REPORT_URL: `${API_BASE_URL}/admin/report/purchase-order`,
  GET_PURCHASE_RETURN_REPORT_URL: `${API_BASE_URL}/admin/report/debit-note`,
  GET_QUOTATION_REPORT_URL: `${API_BASE_URL}/admin/report/quotation`,
  GET_SALES_REPORT_URL: `${API_BASE_URL}/admin/report/sales`,
  GET_SALES_RETURN_REPORT_URL: `${API_BASE_URL}/admin/report/sales-return`,
  GET_DASHBOARD_DATA_URL: `${API_BASE_URL}/admin/dashboard`,
  GET_ACCOUNTS_PLANNING_URL: `${API_BASE_URL}/admin/dashboard/accounts-planning`,
  GET_INCOME_REPORT_URL: `${API_BASE_URL}/admin/report/income`,
  GET_EXPENSE_REPORT_URL: `${API_BASE_URL}/admin/report/expense`,
  GET_INVENTORY_REPORT_URL: `${API_BASE_URL}/admin/report/inventory`,
  GET_LOW_STOCK_REPORT_URL: `${API_BASE_URL}/admin/report/low-stock`,
  GET_OUT_OF_STOCK_STOCK_REPORT_URL: `${API_BASE_URL}/admin/report/out-of-stock`,
  STAFF_ACTIVITY_REPORT_URL: `${API_BASE_URL}/admin/reports/staff-activity`,
  CREATE_NEW_EXPENSE_URL: `${API_BASE_URL}/admin/expenses`,
  FETCH_EXPENSES_FOR_LIST_URL: `${API_BASE_URL}/admin/expenses`,
  GET_EXPENSE_URL: `${API_BASE_URL}/admin/expenses`,
  UPDATE_EXPENSE_URL: `${API_BASE_URL}/admin/expenses`,
  DELETE_EXPENSE_URL: `${API_BASE_URL}/admin/expenses`,
  GET_RECURRING_EXPENSES_URL: `${API_BASE_URL}/admin/recurring-expenses`,
  GET_EXPENSE_CHILDREN_URL: `${API_BASE_URL}/admin/expenses`,
  RUN_RECURRING_EXPENSE_NOW_URL: `${API_BASE_URL}/admin/expenses`,
  SET_EXPENSE_RECURRING_STATUS_URL: `${API_BASE_URL}/admin/expenses`,
  FETCH_EXPENSE_CATEGORIES_FOR_LIST_URL: `${API_BASE_URL}/admin/expense-category`,
  CREATE_NEW_EXPENSE_CATEGORY_URL: `${API_BASE_URL}/admin/expense-category`,
  UPDATE_EXPENSE_CATEGORY_URL: `${API_BASE_URL}/admin/expense-category`,
  DELETE_EXPENSE_CATEGORY_URL: `${API_BASE_URL}/admin/expense-category`,
  PETTY_CASH_LIST_URL: `${API_BASE_URL}/admin/petty-cash`,
  ADD_MOUNT_TO_PETTY_CASH_URL: `${API_BASE_URL}/admin/petty-cash`,
  RETURN_AMOUNT_TO_PETTY_CASH_URL: `${API_BASE_URL}/admin/petty-cash`,
  CONVERT_PO_TO_PURCHASE_URL: `${API_BASE_URL}/admin/purchase-order-convert`,
  FETCH_PETTYCASH_TRANSACTION_LIST_URL: `${API_BASE_URL}/admin/petty-cash-transaction`,
  CONFIGURE_INVOICE_NUMBER_URL: `${API_BASE_URL}/admin/create-general-settings`,
  FETCH_NEXT_INVOICE_NO_URL: `${API_BASE_URL}/admin/invoices/next-number`,
  FETCH_BANK_TRANSACTION_LIST_URL: `${API_BASE_URL}/admin/bank-transactions`,
  FETCH_EXPENSE_CATEGORIES_WITH_SEARCH_URL: `${API_BASE_URL}/admin/expense-category-minimal`,
  FETCH_BANKING_CHART_URL: `${API_BASE_URL}/admin/bank-petty-chart`,
  FETCH_BANK_ACCOUNT_WITH_BALANCE_URL: `${API_BASE_URL}/admin/bank-petty`,
  FETCH_TRANSACTIONS_FOR_RECONCILIATION_URL: `${API_BASE_URL}/admin/bank-transactions-reconcile`,
  RECONCILE_TRANSACTION_URL: `${API_BASE_URL}/admin/bank-reconcile`,
  CREATE_CUSTOM_FIELD_URL: `${API_BASE_URL}/admin/custom-fields`,
  FETCH_COUSTOM_FIELDS_URL: `${API_BASE_URL}/admin/custom-fields`,
  UPDATE_CUSTOM_FIELD_URL: `${API_BASE_URL}/admin/custom-fields`,
  DELETE_CUSTOM_FIELD_URL: `${API_BASE_URL}/admin/custom-fields`,
  FETCH_CUSTOM_FIELDS_URL: `${API_BASE_URL}/admin/custom-field-data-types `,
  CREATE_AUTOMATIC_REMINDER_URL: `${API_BASE_URL}/reminders/create-reminder `,
  CREATE_REMINDER_URL: `${API_BASE_URL}/reminders/create-reminder `,
  FETCH_REMINDERS_URL: `${API_BASE_URL}/reminders/get-reminders`,
  UPDATE_REMINDER_URL: `${API_BASE_URL}/reminders/update-reminder`,
  DELETE_REMINDER_URL: `${API_BASE_URL}/reminders/delete-reminder`,
  PLACE_HOLDER_API_URL: `${API_BASE_URL}/reminders/invoice-placeholders`,
  UPDATE_GENERAL_SETTINGS_URL: `${API_BASE_URL}/admin/create-general-settings`,
  GET_GENERAL_SETTINGS_URL: `${API_BASE_URL}/admin/general-settings-list`,
  FETCH_USERS_BY_ROLE_WITH_SEARCH_URL: `${API_BASE_URL}/admin/user-by-role`,
  UPDATE_QUOTATION_STATUS_URL: `${API_BASE_URL}/admin/quotations-status`,
  SEND_QUOTATION_MAIL_URL: `${API_BASE_URL}/admin/quotations/mail`,
  FETCH_TRANSACTION_DETAILS_URL: `${API_BASE_URL}/admin/bank-transactions-details`,
  FETCH_QUOTATION_PLACEHOLDERS_URL: `${API_BASE_URL}/reminders/quotation-placeholders`,
  CREATE_NEW_QUOTATION_REMINDER_URL: `${API_BASE_URL}/reminders/create-reminder-quotation`,
  UPDATE_QUOTATION_REMINDER_URL: `${API_BASE_URL}/reminders/update-reminder-quotation`,
  FETCH_CUSTOM_FIELD_TYPES: `${API_BASE_URL}/admin/field-types`,
  EXTERNAL_SSO_EXCHANGE_URL: `${API_BASE_URL}/external/sso/exchange`,
  GET_GATEWAY_CONFIGS_URL: `${API_BASE_URL}/admin/gateway-configs`,
  UPSERT_GATEWAY_CONFIG_URL: `${API_BASE_URL}/admin/gateway-configs`,
  DELETE_GATEWAY_CONFIG_URL: `${API_BASE_URL}/admin/gateway-configs`,
  // Link-based payment methods (Wise, Revolut, ...) — list/create, then /${id} for update/delete
  PAYMENT_LINK_METHODS_URL: `${API_BASE_URL}/admin/payment-link-methods`,
  GET_PAYMENT_TRANSACTIONS_URL: `${API_BASE_URL}/admin/payment-transactions`,
  GET_PAYMENT_TRANSACTION_URL: `${API_BASE_URL}/admin/payment-transactions`,
  GET_REFUNDS_URL: `${API_BASE_URL}/admin/refunds`,
  GET_BANK_TRANSACTIONS_URL: `${API_BASE_URL}/admin/bank-transactions`,
  CREATE_BANK_TRANSACTION_URL: `${API_BASE_URL}/admin/bank-transactions`,
  DELETE_BANK_TRANSACTION_URL: `${API_BASE_URL}/admin/bank-transactions`,
  IMPORT_BANK_TRANSACTIONS_URL: `${API_BASE_URL}/admin/bank-transactions/import`,
  CONFIRM_IMPORT_BANK_TRANSACTIONS_URL: `${API_BASE_URL}/admin/bank-transactions/import/confirm`,
  SUGGEST_BANK_TX_MATCHES_URL: `${API_BASE_URL}/admin/bank-transactions`, // append /${id}/suggest-matches
  LINK_BANK_TX_URL: `${API_BASE_URL}/admin/bank-transactions`,            // append /${id}/link
  UNLINK_BANK_TX_URL: `${API_BASE_URL}/admin/bank-transactions`,          // append /${id}/unlink
  BANK_TXN_ANALYSE_URL: `${API_BASE_URL}/admin/bank-transactions`,        // append /${id}/analyse
  BANK_TXN_ANALYSE_ALL_URL: `${API_BASE_URL}/admin/bank-transactions/analyse-all`,
  BANK_TXN_APPROVE_URL: `${API_BASE_URL}/admin/bank-transactions`,        // append /${id}/approve
  BANK_TXN_REJECT_URL: `${API_BASE_URL}/admin/bank-transactions`,         // append /${id}/reject
  GET_CUSTOMER_STATEMENT_URL: `${API_BASE_URL}/admin/customers`, // append /${id}/statement?from=&to=
  IMPORT_CUSTOMERS_URL: `${API_BASE_URL}/admin/customers/import`,
  CONFIRM_IMPORT_CUSTOMERS_URL: `${API_BASE_URL}/admin/customers/import/confirm`,
  GET_ACCOUNTS_URL: `${API_BASE_URL}/admin/accounts`,
  CREATE_ACCOUNT_URL: `${API_BASE_URL}/admin/accounts`,
  UPDATE_ACCOUNT_URL: `${API_BASE_URL}/admin/accounts`,
  DELETE_ACCOUNT_URL: `${API_BASE_URL}/admin/accounts`,
  SEED_DEFAULT_ACCOUNTS_URL: `${API_BASE_URL}/admin/accounts/seed-defaults`,
  GET_JOURNAL_ENTRIES_URL: `${API_BASE_URL}/admin/journal-entries`,
  GET_JOURNAL_ENTRY_URL: `${API_BASE_URL}/admin/journal-entries`,
  CREATE_JOURNAL_ENTRY_URL: `${API_BASE_URL}/admin/journal-entries`,
  DELETE_JOURNAL_ENTRY_URL: `${API_BASE_URL}/admin/journal-entries`,
  GET_PROFIT_LOSS_URL: `${API_BASE_URL}/admin/reports/profit-loss`,
  GET_BALANCE_SHEET_URL: `${API_BASE_URL}/admin/reports/balance-sheet`,
  GET_TRIAL_BALANCE_URL: `${API_BASE_URL}/admin/reports/trial-balance`,
  GET_TALLY_CHECK_URL: `${API_BASE_URL}/admin/reports/tally-check`,
  GET_TAX_SUMMARY_URL: `${API_BASE_URL}/admin/reports/tax-summary`,
  GET_GSTR1_URL: `${API_BASE_URL}/admin/reports/gstr-1`,
  GET_GSTR3B_URL: `${API_BASE_URL}/admin/reports/gstr-3b`,
  GET_ACCOUNTING_PERIODS_URL: `${API_BASE_URL}/admin/accounting-periods`,
  CREATE_ACCOUNTING_PERIOD_URL: `${API_BASE_URL}/admin/accounting-periods`,
  UPDATE_ACCOUNTING_PERIOD_URL: `${API_BASE_URL}/admin/accounting-periods`,
  DELETE_ACCOUNTING_PERIOD_URL: `${API_BASE_URL}/admin/accounting-periods`,
  LOCK_ACCOUNTING_PERIOD_URL: `${API_BASE_URL}/admin/accounting-periods`,
  UNLOCK_ACCOUNTING_PERIOD_URL: `${API_BASE_URL}/admin/accounting-periods`,
  EXPORT_GSTR1_URL: `${API_BASE_URL}/admin/gst-filing/gstr-1/export`,
  EXPORT_GSTR3B_URL: `${API_BASE_URL}/admin/gst-filing/gstr-3b/export`,
  // Country tax returns (regime-aware): JSON at the base URL, CSV via `.csv` suffix.
  GET_TAX_RETURN_UK_VAT_URL: `${API_BASE_URL}/admin/tax-returns/uk-vat`,
  GET_TAX_RETURN_AU_BAS_URL: `${API_BASE_URL}/admin/tax-returns/au-bas`,
  GET_TAX_RETURN_NZ_GST_URL: `${API_BASE_URL}/admin/tax-returns/nz-gst`,
  GET_TAX_RETURN_EU_VAT_URL: `${API_BASE_URL}/admin/tax-returns/eu-vat`,
  GET_TAX_RETURN_EU_EC_SALES_LIST_URL: `${API_BASE_URL}/admin/tax-returns/eu-ec-sales-list`,
  // EU OSS (One-Stop-Shop): destination-country return + distance-selling threshold.
  GET_TAX_RETURN_EU_OSS_URL: `${API_BASE_URL}/admin/tax-returns/eu-oss`,
  GET_TAX_RETURN_EU_OSS_THRESHOLD_URL: `${API_BASE_URL}/admin/tax-returns/eu-oss/threshold`,
  // HMRC Making Tax Digital (MTD) VAT — BYOK, off by default + mock mode
  MTD_CONFIG_URL: `${API_BASE_URL}/admin/mtd/config`,
  MTD_AUTH_URL: `${API_BASE_URL}/admin/mtd/auth-url`,
  MTD_OBLIGATIONS_URL: `${API_BASE_URL}/admin/mtd/obligations`,
  MTD_SUBMIT_URL: `${API_BASE_URL}/admin/mtd/submit`,
  MTD_LIABILITIES_URL: `${API_BASE_URL}/admin/mtd/liabilities`,
  GET_E_INVOICES_URL: `${API_BASE_URL}/admin/e-invoices`,
  GET_E_INVOICE_BY_INVOICE_URL: `${API_BASE_URL}/admin/e-invoices/by-invoice`,
  GENERATE_E_INVOICE_URL: `${API_BASE_URL}/admin/e-invoices/generate`,
  CANCEL_E_INVOICE_URL: `${API_BASE_URL}/admin/e-invoices`, // append /${id}/cancel
  GET_ACCOUNTING_INTEGRATIONS_URL: `${API_BASE_URL}/admin/accounting-integrations`,
  CONNECT_ACCOUNTING_INTEGRATION_URL: `${API_BASE_URL}/admin/accounting-integrations`,
  SYNC_ACCOUNTING_INTEGRATION_URL: `${API_BASE_URL}/admin/accounting-integrations`,
  DISCONNECT_ACCOUNTING_INTEGRATION_URL: `${API_BASE_URL}/admin/accounting-integrations`,
  GET_MESSAGING_CONFIG_URL: `${API_BASE_URL}/admin/messaging/config`,
  UPSERT_MESSAGING_CONFIG_URL: `${API_BASE_URL}/admin/messaging/config`,
  SEND_WHATSAPP_URL: `${API_BASE_URL}/admin/messaging/whatsapp/send`,
  SEND_INVOICE_WHATSAPP_URL: `${API_BASE_URL}/admin/invoices`, // append /${id}/send-whatsapp
  // Cluster H — slice H.1 (BYOK AI config)
  AI_CONFIG_URL: `${API_BASE_URL}/admin/ai/config`,
  AI_CONFIG_TEST_URL: `${API_BASE_URL}/admin/ai/config/test`,
  // Cluster H — slice H.2 (bill OCR → draft purchase)
  AI_EXTRACT_BILL_URL: `${API_BASE_URL}/admin/ai/extract-bill`,
  // Cluster H — slice H.3 (streaming co-pilot chat)
  AI_CHAT_URL: `${API_BASE_URL}/admin/ai/chat`,
  AI_CHAT_SESSIONS_URL: `${API_BASE_URL}/admin/ai/chat/sessions`,
  // Cluster H — slice H.4 (usage logs + cost reporting)
  AI_USAGE_URL: `${API_BASE_URL}/admin/ai/usage`,
  AI_USAGE_SUMMARY_URL: `${API_BASE_URL}/admin/ai/usage/summary`,
  // Cluster I — activity log (audit trail)
  GET_ACTIVITY_LOGS_URL: `${API_BASE_URL}/admin/activity-logs`,
  // Ledger Setup Wizard
  FETCH_LEDGER_STATUS_URL: `${API_BASE_URL}/admin/ledger/status`,
  FETCH_LEDGER_COUNTRY_PACKS_URL: `${API_BASE_URL}/admin/ledger/country-packs`,
  POST_LEDGER_SETUP_URL: `${API_BASE_URL}/admin/ledger/setup`,
  FETCH_LEDGER_CUTOVER_PREVIEW_URL: `${API_BASE_URL}/admin/ledger/cutover/preview`,
  POST_LEDGER_CUTOVER_COMMIT_URL: `${API_BASE_URL}/admin/ledger/cutover/commit`,
  // Finance Report pages
  FETCH_AR_AGING_URL: `${API_BASE_URL}/admin/reports/ar-aging`,
  FETCH_AP_AGING_URL: `${API_BASE_URL}/admin/reports/ap-aging`,
  FETCH_COLLECTIONS_URL: `${API_BASE_URL}/admin/reports/collections`,
  FETCH_BUDGET_VARIANCE_URL: `${API_BASE_URL}/admin/reports/budget-variance`,
  FETCH_CASH_FLOW_FORECAST_URL: `${API_BASE_URL}/admin/reports/cash-flow-forecast`,
  FETCH_PNL_BY_COST_CENTER_URL: `${API_BASE_URL}/admin/reports/pnl-by-cost-center`,
  FETCH_PNL_BY_PROJECT_URL: `${API_BASE_URL}/admin/reports/pnl-by-project`,
  FETCH_PNL_BY_DEPARTMENT_URL: `${API_BASE_URL}/admin/reports/pnl-by-department`,
  FETCH_COST_CENTERS_URL: `${API_BASE_URL}/admin/cost-centers`,
  CREATE_COST_CENTER_URL: `${API_BASE_URL}/admin/cost-centers`,
  UPDATE_COST_CENTER_URL: `${API_BASE_URL}/admin/cost-centers`,
  DELETE_COST_CENTER_URL: `${API_BASE_URL}/admin/cost-centers`,
  FETCH_PROJECTS_URL: `${API_BASE_URL}/admin/projects`,
  CREATE_PROJECT_URL: `${API_BASE_URL}/admin/projects`,
  UPDATE_PROJECT_URL: `${API_BASE_URL}/admin/projects`,
  DELETE_PROJECT_URL: `${API_BASE_URL}/admin/projects`,
  FETCH_BUDGETS_URL: `${API_BASE_URL}/admin/budgets`,
  CREATE_BUDGET_URL: `${API_BASE_URL}/admin/budgets`,
  UPDATE_BUDGET_URL: `${API_BASE_URL}/admin/budgets`,
  DELETE_BUDGET_URL: `${API_BASE_URL}/admin/budgets`,
  FETCH_FIXED_ASSETS_URL: `${API_BASE_URL}/admin/fixed-assets`,
  SEARCH_FIXED_ASSETS_URL: `${API_BASE_URL}/admin/fixed-assets/search`,
  CREATE_FIXED_ASSET_URL: `${API_BASE_URL}/admin/fixed-assets`,
  UPDATE_FIXED_ASSET_URL: `${API_BASE_URL}/admin/fixed-assets`,
  DELETE_FIXED_ASSET_URL: `${API_BASE_URL}/admin/fixed-assets`,
  RUN_DEPRECIATION_URL: `${API_BASE_URL}/admin/fixed-assets/run-depreciation`,
  DISPOSE_FIXED_ASSET_URL: `${API_BASE_URL}/admin/fixed-assets`,
  FETCH_COST_LAYERS_URL: `${API_BASE_URL}/admin/inventory/cost-layers`,
  // Approvals queue
  FETCH_PENDING_APPROVALS_URL: `${API_BASE_URL}/admin/approvals/pending`,
  // Document Defaults (D.1 / D.2)
  GET_DOCUMENT_DEFAULTS_URL: `${API_BASE_URL}/admin/document-defaults`,
  UPDATE_DOCUMENT_DEFAULTS_URL: `${API_BASE_URL}/admin/document-defaults`,
  // Money In / Money Out (transaction types, categories, explain)
  GET_TRANSACTION_TYPES_URL: `${API_BASE_URL}/admin/transaction-types`,
  TRANSACTION_CATEGORIES_URL: `${API_BASE_URL}/admin/transaction-categories`, // list/create; append /${id} for PUT/PATCH/DELETE
  EXPLAIN_BANK_TXN_URL: `${API_BASE_URL}/admin/bank-transactions`, // append /${id}/explain or /${id}/unexplain
  // Invoice partial-payments (tasks 1-4)
  INVOICE_PAYMENTS_URL: `${API_BASE_URL}/admin/invoices`,         // append /${id}/payments
  INVOICE_ACTIVITY_URL: `${API_BASE_URL}/admin/invoices`,         // append /${id}/activity
  VOID_INVOICE_PAYMENT_URL: `${API_BASE_URL}/admin/invoices/payments`, // append /${paymentId}/void
  // Purchase partial-payments (purchase parity tasks 1-5)
  PURCHASE_PAYMENTS_URL: `${API_BASE_URL}/admin/purchases`,       // append /${id}/payments
  PURCHASE_ACTIVITY_URL: `${API_BASE_URL}/admin/purchases`,       // append /${id}/activity
  VOID_SUPPLIER_PAYMENT_URL: `${API_BASE_URL}/admin/purchases/payments`, // append /${paymentId}/void
  SEND_PURCHASE_MAIL_URL: `${API_BASE_URL}/admin/purchases/mail`,
  // My Money (per-user UK tax year consolidation)
  GET_MY_MONEY_URL: `${API_BASE_URL}/admin/my-money`,
  // Time Tracking — project members + settings
  PROJECT_MEMBERS_URL: (projectId: string) => `${API_BASE_URL}/admin/projects/${projectId}/members`,
  PROJECT_MEMBER_URL: (projectId: string, memberId: string) => `${API_BASE_URL}/admin/projects/${projectId}/members/${memberId}`,
  PROJECT_SETTINGS_URL: (projectId: string) => `${API_BASE_URL}/admin/projects/${projectId}/settings`,
  // Time Tracking — timesheets
  TIMESHEET_WEEK_URL: `${API_BASE_URL}/admin/timesheets/week`,
  TIMESHEET_ENTRIES_URL: (timesheetId: string) => `${API_BASE_URL}/admin/timesheets/${timesheetId}/entries`,
  TIMESHEET_SUBMIT_URL: (timesheetId: string) => `${API_BASE_URL}/admin/timesheets/${timesheetId}/submit`,
  TIMESHEET_APPROVE_URL: (timesheetId: string) => `${API_BASE_URL}/admin/timesheets/${timesheetId}/approve`,
  TIMESHEET_REJECT_URL: (timesheetId: string) => `${API_BASE_URL}/admin/timesheets/${timesheetId}/reject`,
  TIMESHEETS_URL: `${API_BASE_URL}/admin/timesheets`,
  TIMESHEET_AVAILABLE_PROJECTS_URL: `${API_BASE_URL}/admin/timesheets/available-projects`,
  TIMESHEET_JOIN_PROJECT_URL: `${API_BASE_URL}/admin/timesheets/join-project`,
  TIMESHEET_LEAVE_PROJECT_URL: (projectId: string) =>
    `${API_BASE_URL}/admin/timesheets/leave-project/${projectId}`,
  // Time Tracking — reports
  TIME_REPORTS_SUMMARY_URL: `${API_BASE_URL}/admin/time-reports/summary`,
  // Time Tracking — holidays
  HOLIDAYS_URL: `${API_BASE_URL}/admin/holidays`,
  HOLIDAY_URL: (id: string) => `${API_BASE_URL}/admin/holidays/${id}`,
  // Time Tracking — leave types
  LEAVE_TYPES_URL: `${API_BASE_URL}/admin/leave-types`,
  LEAVE_TYPE_URL: (id: string) => `${API_BASE_URL}/admin/leave-types/${id}`,
  // Time Tracking — leave allocations
  LEAVE_ALLOCATIONS_URL: `${API_BASE_URL}/admin/leave-allocations`,
  LEAVE_ALLOCATION_URL: (id: string) => `${API_BASE_URL}/admin/leave-allocations/${id}`,
  // Time Tracking — leave requests
  LEAVE_REQUESTS_URL: `${API_BASE_URL}/admin/leave-requests`,
  LEAVE_REQUEST_URL: (id: string) => `${API_BASE_URL}/admin/leave-requests/${id}`,
  LEAVE_REQUEST_APPROVE_URL: (id: string) => `${API_BASE_URL}/admin/leave-requests/${id}/approve`,
  LEAVE_REQUEST_REJECT_URL: (id: string) => `${API_BASE_URL}/admin/leave-requests/${id}/reject`,
  LEAVE_REQUEST_CANCEL_URL: (id: string) => `${API_BASE_URL}/admin/leave-requests/${id}/cancel`,
  // Time Tracking — leave balances
  LEAVE_BALANCES_URL: `${API_BASE_URL}/admin/leave-balances`,
  // Time Tracking — leave reports
  LEAVE_REPORTS_SUMMARY_URL: `${API_BASE_URL}/admin/leave-reports/summary`,
  // Data Exports (authenticated CSV / full-backup ZIP — fetch as blob, see utils/downloadExport)
  EXPORT_JOURNAL_ENTRIES_URL: `${API_BASE_URL}/admin/export/journal-entries.csv`,
  EXPORT_CHART_OF_ACCOUNTS_URL: `${API_BASE_URL}/admin/export/chart-of-accounts.csv`,
  EXPORT_INVOICES_URL: `${API_BASE_URL}/admin/export/invoices.csv`,
  EXPORT_INVOICE_ITEMS_URL: `${API_BASE_URL}/admin/export/invoice-items.csv`,
  EXPORT_CUSTOMERS_URL: `${API_BASE_URL}/admin/export/customers.csv`,
  EXPORT_PRODUCTS_URL: `${API_BASE_URL}/admin/export/products.csv`,
  EXPORT_BANK_TRANSACTIONS_URL: `${API_BASE_URL}/admin/export/bank-transactions.csv`,
  EXPORT_TRIAL_BALANCE_URL: `${API_BASE_URL}/admin/export/trial-balance.csv`,
  EXPORT_BALANCE_SHEET_URL: `${API_BASE_URL}/admin/export/balance-sheet.csv`,
  EXPORT_PROFIT_AND_LOSS_URL: `${API_BASE_URL}/admin/export/profit-and-loss.csv`,
  EXPORT_AR_AGING_URL: `${API_BASE_URL}/admin/export/ar-aging.csv`,
  EXPORT_AP_AGING_URL: `${API_BASE_URL}/admin/export/ap-aging.csv`,
  EXPORT_BACKUP_URL: `${API_BASE_URL}/admin/export/backup.zip`,
};

export default Constants;
